# Generated by Django 4.2.6 on 2023-11-12 16:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
