# Generated by Django 4.2.6 on 2023-11-12 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_autos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='fecha_de_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='autos',
            name='modelo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
