# Generated by Django 4.2.6 on 2023-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_autos_fecha_de_creacion_autos_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='imagen_a_agregar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
